### ISSUE TITLE
click next after stage 1 does nothing

### ISSUE THREAD

**Issue by gubuntu** [hotosm/field-campaigner#100]

**Comment by dimasciput** [comment]
Could you elaborate more? I can't reproduce this error.

**Comment by gubuntu** [comment]
Sorry @dimasciput I had responded to you in Gitter:
>ah I just noticed the faint red line around campaign manager (I couldn’t add myself) so I chose Christian. Now I’m on the next screen

So perhaps the issue should be 'allow user to add themselves as campaign manager'
