### ISSUE TITLE
Workflow for adding remote mapping tracking

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#109]
Related to #6. Need to have a workflow within the campaign creation to add remote mapping tracking from the Tasking Manager.

We can start out with just linking through project URLs and the API. But future considerations should include interacting with the Tasking Manager 3.0 API to create new projects (this would be based on the Field Campaign AOI).

**Comment by dimasciput** [comment]
Search based on aoi in tasking manager api is using some token, and I couldn't figured out where to get that. In the meantime, adding remote mapping tracking will use a search button https://github.com/hotosm/field-campaigner/pull/151
