### ISSUE TITLE
Improving how to add and update field coverage areas

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#111]
Related to #5, adding shapefile for showing field coverage is slightly confusing. There is some confusion with the difference between the campaign AOI and field mapping coverage. 

Couple priorities I think came about from testing: 

1. We may want to think about this as a default instead of an add-on. You are always tracking coverage - whether it is one area or multiple areas split by team. 

2. Need clear instructions for adding. What is needed? How do you split an area up? 

3. Do we need to think about integrating some type of online updating of the areas? Maybe take a queue from http://geojson.io and how you can manage a table view?

**Comment by cchristelis** [comment]
This will be covered by a better workflow.

**Comment by cchristelis** [comment]
[Uploading Campaign2-3.png...]
