### ISSUE TITLE
Map view: custom imagery/TMS

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/field-campaigner#112]
A number of field mapping projects use custom imagery and/or TMS services. Would be very useful for logistics, team/task distribution etc if these could be accessed from the main map view (I know FieldPapers had this functionality before)

**Comment by cchristelis** [comment]
# Proposed Solution

Add an "alternative imagery" attribute to the project and if the user has populated this we use that in the dashboard views.

**Comment by PaulUithol** [comment]
Would be great if you could still switch between map to aerial imagery view (simple layer switcher),
