### ISSUE TITLE
Add a FieldPapers geojson endpoint

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#113]
One consideration for splitting up an area is based on Field Papers. Each atlas that is made, gets a geojson endpoint. That geojson endpoint could be imported and used as the split for the coverage. 

Example: http://fieldpapers.org/atlases/50spxcuy.geojson.

**Comment by meomancer** [comment]
maybe we need to update UI too for this coverage method
CC @MariaSolovyeva

**Comment by MariaSolovyeva** [comment]
What is the workflow for loading the atlas, does it need any specific actions from a user? Currently I  just added a button so user could upload the atlas clicking on it

![createcampaign-workflow-fieldpapers](https://user-images.githubusercontent.com/10400420/28416299-21173d32-6d5c-11e7-8804-4b3cd0a94985.png)

**Comment by cchristelis** [comment]
@MariaSolovyeva, I think we'll also need some helper text to explain this to the user, could you mock that up. 
@smit1678 helper text could be along the lines of:
> The AOI is specified in one of the following ways:
> Digitising on the map.
> Upload a SHP file which either has only one polygon containing the AOI or multiple polygons each indicating a campaign area. Teams can be assigned in this file by adding a "team" column and the status is deduced from a "date" column indicating on which date the team will complete their mapping. When using multiple polygons these must be union-able into a single polygon.
> Upload a FieldPagers Atlas.

**Comment by MariaSolovyeva** [comment]
Here is the one with the text:

![createcampaign-workflow-fieldpapers](https://user-images.githubusercontent.com/10400420/28417121-8262015a-6d5f-11e7-987f-33d92f2d2e50.png)
