### ISSUE TITLE
Workflow for adding insight functions

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#118]
Feedback from user testing: Insight functions are slightly confusing. Need addition descriptive text, but also could review the interaction with them. What is default versus what is optional? What is the interaction for how to track multiple tags?

**Comment by cchristelis** [comment]
We need to auto add these based on the templates produced in #120.

**Comment by meomancer** [comment]
after https://github.com/hotosm/field-campaigner/issues/120 is implemented, i think we don't need `feature` and `attributes` input in insight function, instead just choose what insight function to be used

**Comment by cchristelis** [comment]
@meomancer, I think that we still need these, but after #120, we'll have these pre-populated...
