### ISSUE TITLE
Create example simple surveys

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#120]
Need to add some examples of simple health facility or education surveys that can be used for testing. Complex survey example here: https://github.com/osmlab/field-data-collection/tree/master/data/surveys

**Comment by smit1678** [comment]
Example surveys to do list: 

- urban examples
  - [ ] Maps.me
  - [ ] OpenMapKit
  - [ ] other 
- rural examples
  - [ ] Maps.me
  - [ ] OpenMapKit
  - [ ] other

**Comment by PaulUithol** [comment]
Urban:
- Ramani Huria data model - https://docs.google.com/document/d/1KaQNZGoXlAQhhYUPXy1EehbqP9ds0ZV9r5andoTVgtc/

Rural/urban:
- Financial services, Uganda - https://github.com/hotosm/MapUganda/tree/master/data%20model

**Comment by smit1678** [comment]
@MariaSolovyeva @cchristelis Here is an example list of items being collected for financial services: https://gist.github.com/smit1678/f4f42e9e5b76ddbdd0b81ba93aac4e0a. You'll see the features and matching tags (plus options if any). This is from the financial services work in Uganda. 

Will post some other examples later today.

**Comment by smit1678** [comment]
Another health facility survey: https://gist.github.com/smit1678/a355159f4efba0f91d4a105a905a7296

**Comment by smit1678** [comment]
@cchristelis An example OMK form: https://drive.google.com/file/d/0B0qNVunoiiLmY0NPQTZ3bnpMVlk/view?usp=sharing
