### ISSUE TITLE
Improve/optimize feature counts and error checking

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#127]
Seeing a couple differences in feature counts. Summarizing below to start the discussion around what is tracked and how. 

I created a small campaign around an island that has one building: https://staging.campaign.kartoza.com/campaign_manager/campaign/a250b51656ed4a59a6b96cf60f2ff7a2. It has one building (but also a relation -- there is a wall around the building). 

When looking at the insight functions: 

## Showing number of feature in group for buildings

There is only one building shown: 
![](https://api.monosnap.com/rpc/file/download?id=sosaLIj1wMGfoyAW6rH9CKKjIoGttu)

## Showing feature completeness for buildings with attributes man_made=lighthouse

There are two issues here. One is that the percentage of feature completeness is off. It is correct that there is only one feature with `man_made=lighthouse` but it shows 56 other features. 

Then in the table view, it shows two entries. One of which is not the building OSM id: http://www.openstreetmap.org/way/249486506. 

![](https://api.monosnap.com/rpc/file/download?id=alNXJwT0WDyISthPWWIGjY03OOBESL)

**Comment by dimasciput** [comment]
update in https://github.com/hotosm/field-campaigner/issues/142

**Comment by MariaSolovyeva** [comment]
To add some order in the graphs/numbers display, I propose to update a little the functions group part:

- Increase the the font size of percent or simple  number (1st and 3rd columns)
- If there is no need in a percentage/bar, show only the number (see the 3rd column)
- I there are few graphs per function, or if it has a datatable, show up only first graph, and show/hide list of the other features on click
- Display the main  graphs in the rows of 3 col each

![graphs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46ef869b338a90ebc3abaf51ab57f5973d047d317c5ca67f7283b62deb167d560a564eac49505f42f5fcdb2fb4aa2e32db025fb28c341521842f1bbeba8415be05b3288b4b87bfba8f45c3ed2f68.png)

**Comment by smit1678** [comment]
@MariaSolovyeva What would you suggest as alternatives to the pie chart? Pie charts get hard to read when more than a couple items and make them hard to read or interpret. What do we want to communicate here and can we do that in a better way than a pie chart?

**Comment by smit1678** [comment]
@meomancer @cchristelis Can you update the ticket here with what you did to close this out? Interested in understanding the changes made and the approach to handle the issue?

**Comment by meomancer** [comment]
hi @smit1678 
i'm sorry i moved it, due to looking the PR that is merged, but didn't see it is still in progress

**Comment by dimasciput** [comment]
Updated here https://github.com/hotosm/field-campaigner/issues/199
