### ISSUE TITLE
Improve OSMCHA filtering 

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#130]
OSMCHA returns data that is technically outside of the campaign area but since the campaign area falls within the changeset bounding box, it is included. Need to determine some ways to filter out non-relevant changesets. 

One idea would be to filter out edits based on criteria from the source, editor. This isn't perfect because some local editing happens with paper and then in JOSM or iD (instead of using a mobile data collection app). 

Example whole world bounding box edit ([49252126](https://osmcha.mapbox.com/49252126/)):
![osmcha - changeset 49252126 2017-06-15 14-18-48](https://user-images.githubusercontent.com/796838/27183151-8ed502de-51d5-11e7-8745-83d93b4a9f6b.png)

example local edit with iD ([46620284](https://osmcha.mapbox.com/46620284/)): 
![osmcha - changeset 46620284 2017-06-15 14-33-16](https://user-images.githubusercontent.com/796838/27183745-a23dfcf2-51d7-11e7-8837-cd2b6f27335c.png)

**Comment by smit1678** [comment]
@dimasciput Can we look at this again? When looking through the OSMCHA docs, there is a bbox area bounds filter: https://osmcha.mapbox.com/filters. Could we look to implement that based on the campaign size? This in theory would get rid of the changsets with bounding boxes that cover the whole world. 

Are there some other filters we could use to reduce the list that is returned from OSMCHA?

**Comment by cchristelis** [comment]
[Uploading Screen Shot 2017-09-06 at 1.28.36 PM.png...]

**Comment by cchristelis** [comment]
<img width="916" alt="screen shot 2017-09-06 at 1 28 36 pm" src="https://user-images.githubusercontent.com/2319504/30109639-60320c1a-9307-11e7-9fcb-e9d3928a3dd1.png">
