### ISSUE TITLE
Update Coverage Behaviour

### ISSUE THREAD

**Issue by meomancer** [hotosm/field-campaigner#140]
# Problem
Now for uploading coverage, campaign need to be assign coverage insight function and upload it in campaign detail in insights function coverage tab.
I think it is not quite right.

# Solution
Move coverage insight function to be a single function like upload boundary, and editing is done in create/update like boundary.

**Comment by cchristelis** [comment]
@meomancer, I wonder whether we shouldn't have more coverage functions before making this call? Or at least let's look at how we are treating remote mapping.

**Comment by cchristelis** [comment]
@meomancer, I've come around to your initial suggestion, let's update it.

**Comment by meomancer** [comment]
need to update wokflow for this method
cc @smit1678 @MariaSolovyeva

**Comment by cchristelis** [comment]
Let's bring this in line with https://camo.githubusercontent.com/059be333ead222a9cf9c36a41759c9fc703d1d97/687474703a2f2f6d6173686173747564696f2e6e65742f332d576f726b466c6f772d757064617465414f492e706e67

**Comment by dimasciput** [comment]
I missed this task detail, because it was assigned to meomancer before. Can you guys give me the detail again? @cchristelis @meomancer

**Comment by dimasciput** [comment]
Added in #223
