### ISSUE TITLE
Multichart/table at one campaign

### ISSUE THREAD

**Issue by meomancer** [hotosm/field-campaigner#157]
# Problem
If we use multi insights function for one campaign, all of chart and table will be replaced by the last data because no unique on each of insight function

# Solution
Create chart and table unique for each of insight function

**Comment by cchristelis** [comment]
@meomancer, this is very important for re-usability!

**Comment by meomancer** [comment]
this is fixed by https://github.com/hotosm/field-campaigner/pull/166
