### ISSUE TITLE
validate campaign date

### ISSUE THREAD

**Issue by ann26** [hotosm/field-campaigner#158]

**Comment by meomancer** [comment]
# Problem
Campaign start date can be earlier than finish date

# Solution
Validate this on javascript level. It is better if evertime finish date/start date is selected, date selected will be limited based on start/finish date
for example:
if user select start date = 1 july 2017, on the finish date, the fisrt date that can be selected is from 1 July 2017
if user select finish date = 10 july 2017, on the start date, the last date that can be selected is up to 10 July 2017
