### ISSUE TITLE
Confusion on status of campaign

### ISSUE THREAD

**Issue by dimasciput** [hotosm/field-campaigner#169]
Questions: 

- Can we get the status of campaign from the start and the end date? So if the end date is before today then it's automatically finished. I think we can remove the status of campaign option.
![screen shot 2017-07-12 at 1 12 47 pm](https://user-images.githubusercontent.com/1979569/28104158-e7beae98-6703-11e7-8358-cf25a6c7f1a7.png)

- How a campaign gets inactive? Currently there's no procedure for that.

@smit1678 @cchristelis

**Comment by smit1678** [comment]
@dimasciput I think this makes sense. Is there a situation where it would be needed to immediately make a campaign inactive? If that's the case, then a user would need to just change the date to mark the new end date. Does that seem right? I think we'll want to make sure that is clear to the user.
