### ISSUE TITLE
Link to OMK or other data collection forms

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#17]
When creating or managing a campaign, enable links to OMK or other forms for data collection apps that integrate and edit OSM. 

Out of scope at the moment is generating OMK or other data collection forms.

**Comment by dimasciput** [comment]
@smit1678 is there an example for the OMK form link that I can use? Couldn't find the OMK form link in the internet, because OMK is a mobile app. 

Or user just need to upload some form file that can be used in the OMK?

**Comment by smit1678** [comment]
@dimasciput I think what we do now is just open up the app. So the buttons that link to OMK and Maps.me, just open up the mobile apps.
