### ISSUE TITLE
Completeness data source

### ISSUE THREAD

**Issue by meomancer** [hotosm/field-campaigner#170]
# Problem
Now we are divided insight function between overpass and OSMCHA

# Solution
Make it paralelly for one insight function. If overpass giving a lot of time, us OSMCHA instead

**Comment by meomancer** [comment]
hello @batpad @willemarcel
we want to intergrate OSMCHA as a source of error check
Our workflow is updated now. For every check, we filter it by amenity value.

is there any query that we could use for filtering by tags value?
for example is `amenity"~"hospital|doctor"` on overpass

and also, when we try to call http://osmcha-django-staging.tilestream.net/api-docs/#!/features/features_list, using tags to just get features that has amenity in tags, i got error 500

thank you

**Comment by willemarcel** [comment]
Hi @meomancer,

We don't have all the features in the OSMCHA database, we have only the ones that [osm-compare](https://github.com/mapbox/osm-compare) evaluates as suspicious/wrong. Right now our API doesn't allow to filter features by the OSM tags (the tags field that you see in the api-docs is a label that the users can add to changesets and features when reviewing, adding things like: vandalism, resolved, unresolved, severity low/high).

Could you give more details about your use case? We could allow to search features by its OSM tags, but as we don't have all features in our database, the results will not be the same as an overpass query. More details about it https://github.com/mapbox/osmcha-frontend/issues/151#issuecomment-314102769

**Comment by meomancer** [comment]
we need much like https://github.com/mapbox/osmcha-frontend/issues/151
so we need all osm tag, and maybe just filter it by amenity

the use case is
for example: we need to get all of healthsites facilities in AOI (amenity = hospital, doctor, clinic)
after that, we check the tags of OSM, to check if this tags is complete (we make a list of tag that need to be done) or value of tag need to be in the list

**Comment by cchristelis** [comment]
This will be resolved with the dedicated overpass sever.
