### ISSUE TITLE
UI: Share & Participate

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#174]
# Problem 

The calls to action by parcicipants involve sharing the campaign have several options, 3 possibilities for mobile data collection and sharing via Facebook, Twitter and potentially others. This needs to be presented to the user in a consumable way.

# Proposed Solution

Update the dashboard, without the dashboard feeling cluttered or the buttons gettings lost.

**Comment by MariaSolovyeva** [comment]
Hi @cchristelis , what are the mobile data collection possibilities? should they be displayed as buttons with the name or icon?

**Comment by cchristelis** [comment]
@MariaSolovyeva, at the moment we have `OMK` and `maps.me`

**Comment by MariaSolovyeva** [comment]
Hi @cchristelis , attached are two options, the difference is that on the first the mobile share options re on the separate row

![campaign-dashboard-share-1](https://user-images.githubusercontent.com/10400420/28269337-5669622a-6b0a-11e7-9b9f-dc8758362e37.png)
![campaign-dashboard-share-2](https://user-images.githubusercontent.com/10400420/28269338-566a3c4a-6b0a-11e7-876e-bac18c634963.png)

**Comment by smit1678** [comment]
I think I lean towards the second version. I also think these buttons need some action wording. Like `Open OMK` or `Open Maps.me`. These buttons should be focused on getting the user out of the campaign dashboard and into the mobile apps so they can start to contribute to the campaign.

**Comment by cchristelis** [comment]
Great, also I'd like to take @dimasciput's attention to this task.
