### ISSUE TITLE
Promote a campaign

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#18]
Need to integrate ways to promote a campaign. Goal here is to enable wider communication and awareness of a campaign.

Ideas: 
  * Push out to social media
  * Push alerts to apps -- Maps.me

This needs to be define a bit more.

**Comment by cchristelis** [comment]
# Proposed Solution

For the social media, let's add a share option. 
For general integration let's add a checkbox that can be used as a flag for future integrations.

**Comment by cchristelis** [comment]
Let's add the share button in the upper right (management summary) box on the campaign dashboard page.

**Comment by dimasciput** [comment]
<img width="602" alt="screen shot 2017-07-14 at 3 55 23 pm" src="https://user-images.githubusercontent.com/1979569/28205592-e061e3a4-68ac-11e7-8640-92cbf1f5d8f5.png">
