### ISSUE TITLE
Tab of insights function broken if it is too long

### ISSUE THREAD

**Issue by meomancer** [hotosm/field-campaigner#181]
# Problem
When we create a lot of insights for one campaign, it could make tab quite broken, because it is too long for the wrapper.
![selection_014](https://user-images.githubusercontent.com/4530905/28197211-9662333a-687f-11e7-8b2d-50ea89f90b74.png)

# Solution
Options : 
- we make it scrollable-x
- we make this tab in the left side (as horizontal list) and the insights is in the right side

**Comment by cchristelis** [comment]
# Proposed Solution

@meomancer, I think the better solution is to implement this according to the mockups. See: 
![campaign2-2](https://user-images.githubusercontent.com/2319504/28202865-826ddb52-6877-11e7-8476-fdcd9d7815dd.png)


@MariaSolovyeva, please update if this is not the latest.

**Comment by meomancer** [comment]
hi @cchristelis 
now we can have many types
maybe we could update the mokup to show multiple completeness (because completeness is rendered for each type)

or if we choose 2 or more type, will it be shown in one completeness?

**Comment by dimasciput** [comment]
@cchristelis @MariaSolovyeva 
This is like what I said yesterday, we can combine the completeness and count feature and just shows up the title by Type name. But before we go forward with this, I think we need to finalized the mockup.

**Comment by cchristelis** [comment]
Agreed. Let's show the types as the tab items on the left, and group insights accordingly. So we should definately show the functions with the correct data in the correct tab :)

**Comment by MariaSolovyeva** [comment]
Hi @all here is the latest mock-up

![campaign2](https://user-images.githubusercontent.com/10400420/28208983-2588bb4c-6899-11e7-9de2-507490887cbc.png)
