### ISSUE TITLE
Name of this tool

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#19]
We currently have a placeholder name of `field-campaigner`. Previous versions included `map-campaigner`. We need a better name.

**Comment by smit1678** [comment]
Updating progress here with notes from group brainstorming session that happened during a project gathering of HOT staff on June 28: https://docs.google.com/document/d/1JNUSNjotQ0rTYPf0hvGA0cOCKrXIXEImAuRgLco0zT8/edit?usp=sharing. 

To recap, the short-list of names is: 

* Surveyor
* FieldLink
* MapComplete
* Remote2Field
* Ground Link
* MapShop
* OSManager
* Mapsterpiece
* MapCampaigner
* MapMan
* Get Things Mapped
* MapStop
* MapSpace
* ProcessMap
* Create A Map
* Map Collect
* Gather & Map

### Next action here: 

I think based on the list that was generated, there needs to be some more discussion. There are some good potential names but it may be helpful to get some additional input and perhaps a vote together for a name. I think it's worthwhile waiting until the internal release is completed. A running version of the app could be used to help think through a final name.

**Comment by cchristelis** [comment]
Please vote here: https://www.loomio.org/p/JpvHEe9f/name-this-tool

**Comment by PaulUithol** [comment]
Missed this.. it tells me "You do not have permission to do this.". Did we post this to mailinglists etc?

**Comment by cchristelis** [comment]
https://www.loomio.org/p/yNg5atKn/name-this-tool

**Comment by cchristelis** [comment]
MapCampaigner was the selected name.
