### ISSUE TITLE
Implement Tabs

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#207]
# Problem

The tabs should show:
- [x] Groupings with individual insights functions
- [x] Show/hide 
- [x] Summary component (Insight functions have any number of the following: map component, summary component and dashboard details component.)

# Proposed Solution

Implement this.

**Comment by dimasciput** [comment]
@cchristelis , how do you calculate the size of the task? I'm just curious. Because for me this task is not the size of 2.

**Comment by cchristelis** [comment]
@dimasciput, I added that as an estimate of the remainder of the issue. Let's update it if it was a way off estimation.
