### ISSUE TITLE
Advanced mode

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#208]
- [ ] Enable adding/removing tags in Basic mode
- [ ] Restructure Functions section
  - [ ] Change Basic/Advanced dropdown to Button
  - [ ] Add text editing view of campaign details/settings

Enable adding/removing tags in Basic mode: 
![](https://api.monosnap.com/rpc/file/download?id=ajLN4KDUaaOcggM9AEBtNibNCLvIrm)

Restructure functions section: 
![](https://api.monosnap.com/rpc/file/download?id=KWrm0lcdBhWCaF4WFGgJUlHldPjXQx)

**Comment by cchristelis** [comment]
Possible discussion, are we going to be using YAML or JSON?

**Comment by cchristelis** [comment]
@meomancer, what is your preference on the format?

**Comment by meomancer** [comment]
hi @cchristelis @smit1678  
i prefer YAML, but i think we could receive 2 format, which are yaml and json, and there is tab under it to change yaml and json (we could use a hint of format in the top of it (or maybe input hint in the textbox?), and when change the tab, it will show different hint.

and also maybe my question is, this textbox mostly guiding user to fill it based on what insight function they want to use and what features that may they want to use to that insights, isn't it?

**Comment by cchristelis** [comment]
@meomancer, if it is, all the same, I think we should go for YAML. The rationale is that two formats end up being confusing. The only question is how we handle the Geometries?

In terms of this only being a insights function editing area, not at all, we should have the entire campaign's data. So the user gets a view on the file that is being saved.

**Comment by meomancer** [comment]
hi @cchristelis 
after i check, it seems that we need to in json format, because AOI is in geojson format

**Comment by meomancer** [comment]
hi @cchristelis 
the task is quite big for me
it is change a lot and sizee 5 is not enough for me (i already spent 8 last friday and still continue it to handle couple of input from user today)
so maybe 12 is for me

**Comment by dimasciput** [comment]
Added https://github.com/hotosm/field-campaigner/pull/218
