### ISSUE TITLE
osm-reporter app at root url

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#212]
When running the app locally, the OSM Report application is still available at the root URL `http://localhost:64000/`. Is this necessary or required? Seems potentially confusing for new developers or routing users when this is deployed. 

![openstreetmap reporter 2017-07-19 13-15-57](https://user-images.githubusercontent.com/796838/28366411-801f2638-6c84-11e7-8d2c-4855ce694a4f.png)

**Comment by cchristelis** [comment]
# Proposed Solution

@smit1678, let's make the campaign page the homepage and move this to `/reporter`

**Comment by smit1678** [comment]
@cchristelis Is there a purpose for having it included?

**Comment by cchristelis** [comment]
hmm, actually come to think of it, it is just the API views that are important to us...

# Updated Solution

Remove the reporter view altogeth! (and change the url of the capmaing page to `/`)
