### ISSUE TITLE
Turn on all insights functions by default

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#214]
For every campaign, we should default to having all insights functions on.

**Comment by cchristelis** [comment]
@smit1678, although there are some that make sense on a campaign level. Most only make sense once a type of campaign is selected. (All of these are automatically on already)

**Comment by smit1678** [comment]
I'm not seeing these automatically on when I create a new campaign. I have to go into Advanced mode and add them. For every campaign regardless of type, we want to track completeness, errors, and engagement. I do agree that details of how completeness and errors are dependent on the tags that are being collected.
