### ISSUE TITLE
Dashboard User Engagement Tab Missing

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#226]
# Problem

Currently we have all the campaign types insights functions in the tabs, but not the user engagement.

# Proposed Solution

Add this to the tab and allow the same show/hide engagement as per the campaign type tabs.

**Comment by dimasciput** [comment]
@cchristelis This has been added

![map_campaigner_-_mapper_engagement](https://user-images.githubusercontent.com/1979569/28504519-c67d9b02-7042-11e7-84ad-778e51ad4d1d.png)
