### ISSUE TITLE
Dashboard Stuck

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#227]
# Problem

Currently the dasboard of Campaign 2 (https://staging.campaign.kartoza.com/campaign/96224fd319834166b3dbc564d9e98a15) is stuck on `Loading Data`.

# Proposed Solution

Investigate and Fix.

**Comment by dimasciput** [comment]
This just an issue with old data, it has been fixed now 
https://staging.campaign.kartoza.com/campaign/96224fd319834166b3dbc564d9e98a15
