### ISSUE TITLE
Update dashboard view

### ISSUE THREAD

**Issue by dimasciput** [hotosm/field-campaigner#246]
- [x] OSMCHA error and feature completeness in one panel for all of types 
- [x] User engagement in one panel for all of types
- [x] One type view under map at a time

**Comment by smit1678** [comment]
Reopening to add a couple items to match mockups: 

- [ ] Add Areas Covered % to map side panel
- [ ] Update text `Attribute Completeness`, not `Feature completeness`

**Comment by dimasciput** [comment]
@smit1678 how do you calculate the areas covered?

**Comment by smit1678** [comment]
@dimasciput I used a geojson file

**Comment by smit1678** [comment]
Link to campaign: https://staging.campaign.kartoza.com/campaign/115a450e7b244556b026a05d9be35c76

**Comment by dimasciput** [comment]
@smit1678 I mean the formula to calculate the covered area, completed/total area ?
