### ISSUE TITLE
Not collecting data on amenity=cafe

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#248]
When testing out the amenity=cafe monitoring, the application does not seem to be tracking correctly: https://staging.campaign.kartoza.com/campaign/115a450e7b244556b026a05d9be35c76. 

No data is rendered. User engagement is also at zero. I edited within this area yesterday. 

<img width="727" alt="screen shot 2017-07-26 at 11 07 49 am" src="https://user-images.githubusercontent.com/796838/28615915-b2d3a450-71f2-11e7-94d2-e55f031ea569.png">

**Comment by dimasciput** [comment]
I called the overpass api directly and found no cafe there. 

Here's the query 

```
[out:json];
(way["amenity"~"cafe"](poly:"38.72001538543177 -9.135374408215284 38.721325398304785 -9.135374408215284 38.721325398304785 -9.134548287838697 38.72001538543177 -9.134548287838697 38.72001538543177 -9.135374408215284");
 relation["amenity"~"cafe"](poly:"38.72001538543177 -9.135374408215284 38.721325398304785 -9.135374408215284 38.721325398304785 -9.134548287838697 38.72001538543177 -9.134548287838697 38.72001538543177 -9.135374408215284"););(._;>;);
out body;
```

You can check it with http://overpass-turbo.eu.

**Comment by smit1678** [comment]
@dimasciput Not sure why no cafes are being found. I re-ran a query on overpass turbo and it shows 4 cafes in that area: [query results](http://overpass-api.de/api/interpreter?data=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Ccafe%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A%28%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Ccafe%E2%80%9D%0A%20%20node%5B%22amenity%22%3D%22cafe%22%5D%2838.72028396880198%2C-9.13539469242096%2C38.72134076622464%2C-9.134568572044373%29%3B%0A%20%20way%5B%22amenity%22%3D%22cafe%22%5D%2838.72028396880198%2C-9.13539469242096%2C38.72134076622464%2C-9.134568572044373%29%3B%0A%20%20relation%5B%22amenity%22%3D%22cafe%22%5D%2838.72028396880198%2C-9.13539469242096%2C38.72134076622464%2C-9.134568572044373%29%3B%0A%29%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B)

You can see an example node where `amenity=cafe` here: https://www.openstreetmap.org/node/4123536944

**Comment by smit1678** [comment]
@dimasciput Looking closer at the query you posted and it looks like it's not picked up data because you're missing searching nodes in that query.

**Comment by dimasciput** [comment]
@smit1678 yes you are right, ok let's enable the `node`
