### ISSUE TITLE
Search missing from AOI creation step

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#254]
@dimasciput Is there a setup step I'm missing in order to have the search show up? 

![map campaigner 2017-07-27 16-13-00](https://user-images.githubusercontent.com/796838/28677808-8a2f354c-72e6-11e7-9b66-4fb329c70881.png)

**Comment by dimasciput** [comment]
Yes you need to put google api key in secret.py : 
`GOOGLE_API_KEY = '{YOUR-GOOGLE-API-KEY}'`

Follow this step to get the api key → https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by smit1678** [comment]
@dimasciput @cchristelis I was under the assumption that based on [our Slack convo](https://hotosm.slack.com/archives/C4VD2DG4W/p1498124432916759) we would be switching this out. Let's open a new issue if that was never completed.

**Comment by dimasciput** [comment]
I think the other alternative for searching is using http://wiki.openstreetmap.org/wiki/Nominatim.

**Comment by smit1678** [comment]
@dimasciput yeah, let's go with Nominatim. The other idea would be Mapbox.
