### ISSUE TITLE
Too many requests errors

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#265]
@dimasciput @meomancer On our dev server we're occasionally getting Too Many Requests errors from Overpass. 

```
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/web/osm_reporter/campaign_manager/utilities.py", line 97, in run
    fetch_osm(self.file_path, self.url_path)
  File "/home/web/osm_reporter/reporter/osm.py", line 216, in fetch_osm
    raise OverpassDoesNotReturnData
reporter.exceptions.OverpassDoesNotReturnData

Exception in thread Thread-39:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/web/osm_reporter/campaign_manager/utilities.py", line 97, in run
    fetch_osm(self.file_path, self.url_path)
  File "/home/web/osm_reporter/reporter/osm.py", line 216, in fetch_osm
    raise OverpassDoesNotReturnData
reporter.exceptions.OverpassDoesNotReturnData

Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/web/osm_reporter/campaign_manager/utilities.py", line 97, in run
    fetch_osm(self.file_path, self.url_path)
  File "/home/web/osm_reporter/reporter/osm.py", line 216, in fetch_osm
    raise OverpassDoesNotReturnData
reporter.exceptions.OverpassDoesNotReturnData

Error with Overpass
Traceback (most recent call last):
  File "/home/web/osm_reporter/reporter/osm.py", line 208, in fetch_osm
    url_handle = urlopen(web_request, timeout=60)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by meomancer** [comment]
this is because we call overpass for 3 or more insight in one time, and overpass just allow 2 request at one time.
My suggestion is maybe we make some queue for request to overpass, so we could manage request to overpass just up to 2 request in one time.

**Comment by cchristelis** [comment]
Hi @smit1678 and @meomancer, I'm worried queueing will just be a plaster. I can think of a couple of options that would mitigate this issue:
- increase the number of overpass sources.
- ask to have our IP address whitelisted.
- run our own, dedicated overpass instance.
- use an alternative.

**Comment by dimasciput** [comment]
The other option is to use multiple server, so if we run out our quota we switch to other server.

**Comment by cchristelis** [comment]
@dimasciput, perhaps that is the "cheapest" option to but a band-aid on the issue. So I propose that we do go that route. 
But it would also be worth the while to get an estimate on the effort involved with setting up a dedicated instance of overpass...

**Comment by dimasciput** [comment]
There are minimum requirement to run the overpass : (taken from the wiki) 

- 1GB of RAM and sufficient swap space for a small extract or a development system.
- For a full planet with meta and attic data (=all data since license change in September 2012), about 150 GB - 200 GB are required when using a compressed database (since 0.7.52). Without compression at least double the amount is needed.
- Use of fast SSDs instead of slower hard disks is highly recommended!

Then we need to apply the diff minutely or hourly or daily. We need to decide the maximum tolerable lag for our DB. 

For the installation we can do manually or run the docker image.

**Comment by smit1678** [comment]
> this is because we call overpass for 3 or more insight in one time, and overpass just allow 2 request at one time.

@meomancer Is there a way that we could reduce this down to a single call instead of 3?

**Comment by smit1678** [comment]
To recap conversation with @cchristelis, we're going to investigate a few options and look to sync up on Friday for some ways forward. Some related on-going tickets: #130 #170. 

Options we're going to investigate more:  

1. Look to use the Overpass server that is dedicated to the HOT Export Tool. Questions here are if there is extra capacity for use beyond the Export tool and if it's setup for us to use it externally. 
2. Consult more with @batpad @willemarcel about ways to leverage OSMCHA more to replace the use of Overpass. But from #170 we're going to be limited by the fact that its only those that are flagged. So we'd need to address this somehow. 
3. Look to run something ourselves - either Overpass or Docker-OSM. 

Leaning away from Option 3 as that raises the overhead for running this but could consider if we exhaust our other options.

**Comment by dimasciput** [comment]
> @meomancer Is there a way that we could reduce this down to a single call instead of 3?

@smit1678, If we reduce to only one single call, then the query will be more complicated and the results will be a lot bigger. We will get more timeout as a result.

**Comment by mojodna** [comment]
> Look to use the Overpass server that is dedicated to the HOT Export Tool. Questions here are if there is extra capacity for use beyond the Export tool and if it's setup for us to use it externally.

Yes, let's absolutely try to minimize the number of Overpass instances in use for HOT projects (and perhaps Missing Maps leaderboards as that project spins up again). There is currently extra capacity (we run 10 FastCGI processes and only use a maximum of 3 at a time). The current endpoint is http://exports-prod.hotosm.org:6080/, e.g. http://exports-prod.hotosm.org:6080/api/status It updates minutely.

Configuration information is in https://github.com/hotosm/osm-export-tool2/tree/master/ops/docker-overpass-api

@david-hotosm how hard would it be to wire up Overpass statistics to something like [Azure Application Insights](https://azure.microsoft.com/en-us/services/application-insights/) so we can gain a better understanding of scaling needs?

**Comment by mataharimhairi** [comment]
@smit1678 It would be good to discuss with David and Cristiano the requirements of setting up a dedicated server for a HOT Overpass instance to support all our of tools. 

When MapCampaigner starts to get heavily used, it could easily affect the overall performance. If this is discussed soon, Brandon and Seth can help us get that set up.

**Comment by cchristelis** [comment]
This will be resolved with the dedicated overpass sever.
