### ISSUE TITLE
Suitable Interpolation?

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#266]
# Problem

When I look at the participation graph it sometimes looks as though it is moving forward and then again back in time. See the image below:

<img width="369" alt="screen shot 2017-08-01 at 12 15 40 pm" src="https://user-images.githubusercontent.com/2319504/28820967-eb0bfc3a-76b3-11e7-9a79-69f2e97a27f4.png">

# Discussion 

I'm not sure that this is correct and perhaps not fitting the data is appropriate?

**Comment by smit1678** [comment]
@cchristelis I think that's been updated based on the latest `develop` branch: 

![map campaigner - health facilities in jakarta 2017-08-01 11-24-29](https://user-images.githubusercontent.com/796838/28821078-0943184e-76ac-11e7-82e6-b0cd0cd84013.png)

**Comment by cchristelis** [comment]
great.
