### ISSUE TITLE
OSMCHA Error Table Numbers

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#268]
# Problem

The OSMCAH error tables relate to all the changesets which intersect the campaign area and which neither means that the change is limited to our campaign criteria nor that the actual "error" is in our AOI. Only that the AOI intersects with the changeset area. 

# Discussion

Let's add text to inform the user about this fact.

**Comment by dimasciput** [comment]
@cchristelis any suggestion for the wording?

**Comment by dimasciput** [comment]
We already use polygon for this.
