### ISSUE TITLE
Participants Count

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#269]
# Description

At the moment we are counting the number of Project Managers in the Participants Count on the Landing Page.

# Discussion

Should we not rather be using numbers from the user engagement across​ campaigns?

**Comment by dimasciput** [comment]
The user engagement data is not saved in the file, it means we need to save the total user engagement in the file.

**Comment by cchristelis** [comment]
@dimasciput, let's go with your solution.

**Comment by cchristelis** [comment]
This number won't be exact, but it will give a good order of magnitude impression.
