### ISSUE TITLE
Add HOT logo to footer and social share image

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#278]
Logo: http://hot-design-system.s3-website-us-east-1.amazonaws.com/assets/graphics/layout/hot-logo-wo-text.svg

Share image: http://hot-design-system.s3-website-us-east-1.amazonaws.com/assets/graphics/meta/default-meta-image.png

**Comment by dimasciput** [comment]
Is it something like this 
<img width="1076" alt="screen shot 2017-08-11 at 9 25 25 am" src="https://user-images.githubusercontent.com/1979569/29199418-11c20034-7e77-11e7-9c9c-dc48d7eee406.png">

**Comment by smit1678** [comment]
Sorry if the title was confusing. Meant that the social share image is for the meta tags, not put on the page. 

Here's what I was thinking, mainly to simplify: 

- [ ] remove the `HOT is a worldwide nonprofit...` line. 
- [ ] Replace Kartoza logo with HOT logo
- [ ] Add HOT and Kartoza logos to About page
- [ ] replace `Built by` text with `Built by HOT & Partners`, link to About page
- [ ] replace `Available on GitHub!` with `Contribute on GitHub`
- [ ] Add meta tags for proper sharing, use the share image for that: `<meta property="og:image" content="assets/graphics/meta/default-meta-image.png" />`

**Comment by dimasciput** [comment]
@smit1678 

footer : 
<img width="1421" alt="screen shot 2017-08-18 at 8 52 34 am" src="https://user-images.githubusercontent.com/1979569/29440928-b7462b54-83f2-11e7-8cdb-fc3c571d0c81.png">

about page : 
<img width="1301" alt="screen shot 2017-08-18 at 8 52 51 am" src="https://user-images.githubusercontent.com/1979569/29440927-b6efaf36-83f2-11e7-97eb-bae48360b108.png">

**Comment by smit1678** [comment]
@dimasciput 👍
