### ISSUE TITLE
View active campaigns in your area

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#3]
Show active campaigns. Provide navigation to the info/dashboard/mgmt views.

**Comment by cchristelis** [comment]
I think we already are covering this Use Case in the fact that the user's OSM location is used to centre the map. But perhaps a centre button would also be useful?

**Comment by dimasciput** [comment]
@cchristelis we still get all campaign in the home, so if there are a lot of campaign we still unnecessarily getting all of them. I was thinking query with coordinate of user, so it will returns area close to user. Something like `http://0.0.0.0:5000/campaign_manager/?coordinate=-7.559,112.698` 
What do you think?
