### ISSUE TITLE
Add export to JOSM to allow errors to be opened up on JOSM and quickly edited

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#301]
From feedback, add export to JOSM to allow errors to be opened up on JOSM and quickly edited. 

Problem: when you have a long list of errors in the error table, instead of only enabling opening one by one through OSM iD, it would be helpful to enable opening the changesets directly into JOSM. 

See http://wiki.openstreetmap.org/wiki/JOSM/RemoteControl

**Comment by dimasciput** [comment]
@smit1678, Can you explain the workflow? 

Here's what I thought
- User click the link to download josm file from one of the row in error table
- User get the josm file for that node/way
- User open the josm file in josm, and they can edit it

**Comment by cchristelis** [comment]
@dimasciput, let's hang onto this issue for now, getting back to it when all V1 issues are done.
