### ISSUE TITLE
Improve campaign creation wizard layout

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#303]
Feedback from user testing: layout and design of the campaign creation wizard was confusing in the following places: 

* Date hidden and always was skipped
* Previous, Next, and Submit buttons are oddly placed
* Need example description to be helpful to know what to write
* Add clarifying text/layout for Add OMK button.
* Add clarifying text/layout for adding managers. 
* Enable ability to add custom tags. Instead of only having to edit the survey file on Github. 
* Remote mapping workflow is confusing. See separate ticket.
* Confusing when you're in Edit mode (after a campaign has been created) and there isn't a submit button on the main General Information view.

**Comment by MariaSolovyeva** [comment]
Hi @dimasciput , @cchristelis and  @smit1678 

General information:
- I suggest to keep with the homepage buttons colors and make then orange
- Place the date fields below the campaign name
- Add the help text to the campaign description, type, tags and managers - here's some default text I added, @cchristelis maybe you would suggest something better)
- Keep the Next and Previous buttons on the same line and the Submit (for the new campaign)/Update (for the existing campaign, make it visible on the general information tab too) - below them as it works for the whole page, correct?
- Regarding the custom tag which has a value, how about using the colon ":" after the tag name before the value, @meomancer , did you find the solution for this?

![CreateCampaign-WorkFlow-general.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb869f2296868a8ee4af42ad5afed91e4935780f08ac3c3d82e626ba507a0d4d435cec03070511afbd9b21b4b334258e0e5de884695b22c16818acb88a17bf07b325d94b97aaaec81d9ebc6278bec1da0d2c1417198ef55c30a09f4dc850f34de54550a2017b.png)

**Comment by MariaSolovyeva** [comment]
@smit1678 , could you please link here the ticket regarding the remote mapping workflow?

**Comment by dimasciput** [comment]
Thanks @MariaSolovyeva , that layout looks better. @ann26 can you try to implement this? Thanks.

**Comment by ann26** [comment]
ok @dimasciput

**Comment by ann26** [comment]
Hi @MariaSolovyeva , there are two input boxes for start date and end date in the form. Should we remove the upper start date and end date?
![screenshot from 2017-09-29 10-45-45](https://user-images.githubusercontent.com/26101337/31000112-89e34ebc-a503-11e7-8505-6fd2ab475d2b.png)

**Comment by MariaSolovyeva** [comment]
Hi @ann26 I think we can keep the dates on the top, just as the reminders, maybe we can remove editing possibility from there

**Comment by ann26** [comment]
Hi @MariaSolovyeva ok, I have included it in the new ui, please see #374

**Comment by MariaSolovyeva** [comment]
Ok that great, thank you @ann26
