### ISSUE TITLE
Improve dashboard view, map section

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#308]
From feedback, areas to improve: 

### Map Section
* Clarify the participate functionality. Separate the campaign details/management information from the Participate information to help clarify actions. Maps.me and OMK buttons are too hidden to know what to do with them.
* Clarify connection between map, sidebar, and graphs below. Difficult to know that the selected item on the side bar was also related to the graph view below the map. 
* Clarify interaction with the layers on the map. Users did not know they could turn on and off with the eye button. 
* Replace doughnut chart with a bar chart
* White space at top when there is a small description takes up a lot of space
* Improve scalability - not clear you need to scroll if you're tracking more than 3 features on the side bar. Example: http://campaigns-dev.hotosm.org/campaign/541caf2d6a064f0cafc91b71d31468bf. 
* Clarify when/if data is being updated or loaded. Difficult to know whether the data is just slow loading, there is an error, or if the data is being updated in the background.

**Comment by MariaSolovyeva** [comment]
Regarding the dashboard, here's the rough mockup:

- The Maps.me and OMK buttons are moved to the bottom o the campaign description. The "Instructions" button would open a pop-up/tab with instructions. "Participate" button - not sure if we need?
- Connection between map, sidebar, and graphs below: eye icon is unnecessary for the elements which are not displayed on the map. I divided it into 2 icons: "graph" and "map". Clicking on Graph user would toggle the graph, and on Map - toggle the map layer. If the element has no graph or map layer, the icon won't show.
- We should also make smaller the elements height in the sidebar - currently there is  big margin between the feature title and the progress bar - then maybe this will fix the scrolling issue. For the case there are too many elements we can add the arrows in the top and bottom for the sort of vertical carousel scrolling?

![dashboard-wire.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46ec95892b808ca89dedf254ad4ff5d665043761260ea62864c7b96aea1a7e550d094bf9455c0943a9f0892baebe3c76835959e9c3714d36976345f3e5db55ea43a82a994e8dbcbd8f4cc4e03827e188874d391f1755.png)

**Comment by MariaSolovyeva** [comment]
One more thing: do we have to display on the dashboard the areas and teams interactions and statuses? I see it on the map here http://campaigns-dev.hotosm.org/campaign/541caf2d6a064f0cafc91b71d31468bf

**Comment by cchristelis** [comment]
@MariaSolovyeva, perhaps the Manage button would fit into the "Summary box" on the top right?

**Comment by MariaSolovyeva** [comment]
Here's the user and manager views

![Campaign-dashboard.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b285423316546b3397f8fe62bab0021435a571ba8130e5a11f8fddf2cf3bf3c7082540bebd8680d70d42103eee9dc4be05ce36ade0d97bcae8b44cae93825e3828a4c391d06118bfe4f78.png)
![Campaign-dashboard-manager.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b2854233e2405ad2a7780f16af3006b1300051bff054a5556f9f1dc2ff4e039258e585dea84645f74ce3511aab1874dbb13a632c91edbe2e3d7158abd7f37ed998e48341f00188df65836a79a48c050f159ac.png)

**Comment by smit1678** [comment]
@MariaSolovyeva My main point of feedback on the current layout is that the information hierarchy is confusing. Overall campaign summary stats are mixed with the individual feature stats. My sense is that if we separate, there might be better understanding as you move down the page; thoughts? 

![field-campaigner 2017-09-10 22-30-49](https://user-images.githubusercontent.com/796838/30253198-437900b4-9678-11e7-90e5-2df8d125d776.png)

Also, I feel like we're hiding critical information when we put the User Engagement data behind a button and requiring a user to click to see. 

Lastly, I think we should also separate the Maps.me, OMK participate and the share functions. Social sharing seems like it's more of a administrative task and doesn't need to be a primary function.

**Comment by MariaSolovyeva** [comment]
Hello @cchristelis  and @smit1678 

Here what is updated:

- Moved share option to the manager info block
- The summary stats are on the top of the map now
- The summary information functions are not more hidden and also can be srcolled to by clicking on the correspondent tab on the top of the map


![Campaign-dashboard.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b285423316546b3397f8fe62bab0021435a571ba8130e5a11f8fddf2cf3bf3c7082540bebd8680d70d42103eee9dc4be05ce36ade0d97bcae8b4bcae93825e28a8b47381c071e8cf74f78.png)
![Campaign-dashboard-manager.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b2854233e2405ad2a7780f16af3006b1300051bff054a5556f9f1dc2ff4e039258e585dea84645f74ce3511aab1874dbb13a632c91edbe2e3d7158abd7f37ed998e48341f00188cfe593da69b49cd5cf759ac.png)

**Comment by smit1678** [comment]
@MariaSolovyeva Ok great, let's go ahead with these changes - but look to bring in the component styles and colors from TM3, see #313. 

Couple other clarifications: 

1. what happens when I click Instructions? 
2. what happens when there is more than one feature being tracked? how do you interaction with the layers on the map sidebar? 
3. what do the map layers and feature styles look like?

**Comment by smit1678** [comment]
@MariaSolovyeva Also, what do you think of reordering the summary stats to be: Features Collected, Users Engaged, Areas Covered? 

My thinking is for campaigns that only have 1 area, that stat is less important and will sit at 0% until marked complete.

**Comment by MariaSolovyeva** [comment]
hi @smit1678 ok I am updating the styles
regarding your questions:

-  what happens when I click Instructions? I mentioned in the one of the previous comments, it can open a pop up/tab with the instructions copy
-  what happens when there is more than one feature being tracked? how do you interaction with the layers on the map sidebar? - eye icon was unnecessary for the elements which are not displayed on the map. I divided it into 2 icons: "graph" and "map". Clicking on Graph user will toggle the graph below the map, and on Map icon - toggle the map layer. If the element has no graph or map layer, the icon won't show.
-  what do the map layers and feature styles look like? - I think I should firstly address this to @dimasciput as I'm not sure how they are being generated and how far we can edit them on out side
- what do you think of reordering the summary stats to be: Features Collected, Users Engaged, Areas Covered +1, I will show this up in the next image, working on it now

**Comment by MariaSolovyeva** [comment]
Hello @smit1678 and @dimasciput , here is  the updated style, I placed the both user and manager view into it, so please don't be confused.
Regarding the sidebar icons:
- Dark map  icon shows that the layer is visible on the map, 
- Dark graph  icon shows that function graphs are on
- Grey icon shows that map layer is off or the function is available but not shown
- No icon (not shown in the design) means that there is no map layer or detailed function view

![Campaign-dashboard.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b285423316546b3397f8fe62bab0021435a571ba8130e5a11f8fddf2cf3bf3c7082540bebd8680d70d42103eee9dc4be05ce36ade0d97bcae8b4bcae93825e2898e4938180c1a81fd4f78.png)

**Comment by smit1678** [comment]
> what happens when I click Instructions? I mentioned in the one of the previous comments, it can open a pop up/tab with the instructions copy

Ok. 

> what happens when there is more than one feature being tracked? how do you interaction with the layers on the map sidebar? - eye icon was unnecessary for the elements which are not displayed on the map. I divided it into 2 icons: "graph" and "map". Clicking on Graph user will toggle the graph below the map, and on Map icon - toggle the map layer. If the element has no graph or map layer, the icon won't show.

We need to have a more clear indication that the layer can be interacted with. Here is an example campaign with multiple features: http://campaigns-dev.hotosm.org/campaign/541caf2d6a064f0cafc91b71d31468bf. All of them look like they are "active" with the white background in the sidebar. Clicking on the eye only slightly alters the color and doesn't indicate well whats active and what's not active. I'm also not sure it makes sense to have to now have two icons users have to click on. Could we just have a single interaction that helps show that the feature is active and shown on the map plus it has additional information below the map? 

> what do the map layers and feature styles look like? - I think I should firstly address this to @dimasciput as I'm not sure how they are being generated and how far we can edit them on out side

Here's what adding in a remote campaign looks like: http://campaigns-dev.hotosm.org/campaign/87463562c00746b6b7014eac269fa7b3. I think the big questions here are: what are the fill and stroke colors and opacity?

**Comment by MariaSolovyeva** [comment]
Hello @smit1678 , here's anther way to highlight the active layer
![Campaign-dashboard-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b2854233e7b46ef696097ec22ba416f43554d4ba4145c0d12f9ac8d2ff0b169798a5c03e5d16b5671943903b0aac04ee155e57dd205d0f4ae805ec1e13724e28b8a4d3616041e8ffd593db2d4.png)

Regarding the remote campaign border, we can use the secondary HOT color,  the teal one, see below, for @dimasciput  the numbers are :
stroke="#46828f" stroke-opacity="0.8" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" fill="#999" fill-opacity="0.1"

![Campaign-dashboard-remote.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b2854233e3b01ae246480a164fd52690e050a1de853524d41f4ac8d79f0b369748e0a0cb8d86d5f7cce3d17a5bdd01bad1da862da11d1e9e1d30695aa2f2ff58a88453f1b051d8bf75532a19c4fc95ee406.png)

**Comment by dimasciput** [comment]
@MariaSolovyeva I think that's a great idea, will try to implement it now.

**Comment by dimasciput** [comment]
@MariaSolovyeva 
<img width="1346" alt="screen shot 2017-09-13 at 5 03 35 pm" src="https://user-images.githubusercontent.com/1979569/30371688-8f623ab6-98a5-11e7-8487-fd2caacad3a1.png">

We can have multiple remote projects, so what happens if we click the row of the remote projects?

**Comment by MariaSolovyeva** [comment]
@dimasciput , what if we add the opacity to all the remote projects and make only the active one with the opacity "1"? - this is about the map view. For the sidebar, I will think and send you the design shortly

**Comment by MariaSolovyeva** [comment]
Hi @dimasciput , maybe this will work for multiple remote projects

![Campaign-dashboard-remote2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b2854233e3b01ae246480b16af3006b1300051bff054a5556f9f1dc2ff4e039258e585dea84645f74ce3511aab1874dbb13a632c91edbe2e3d7158abd7f37ed998e47341f00188cfc5d34a1984dce5cf359ac.png)

**Comment by MariaSolovyeva** [comment]
Hi @dimasciput , I just thought that to distinguish the remote campaigns we can use other color to highlight them (#46828f - the secondary HOT color)

![Campaign-dashboard-remote3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4bb42b755f29b2854233e3b01ae246480b06af3006b1300051bff054a5556f9f1dc2ff4e039258e585dea84645f74ce3511aab1874dbb13a632c91edbe2e3d7158abd7f37ed998d4f341f00188fff5b35a5984cc158f559ac.png)

**Comment by cchristelis** [comment]
@MariaSolovyeva and @dimasciput, a lot of this has been completed in other tickets. Could you guys update us on the progress here.
