### ISSUE TITLE
Improve dashboard view, error table section

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#309]
From feedback, separation between OSMCHA and attributes is confusing. Users were not sure what to do with each, plus there are some improvements to the table functionality that may help. 

Biggest point of feedback is the separation between the two tables and the need to integrate to make the error table easier to use and understand. 

Idea: combine the two error feeds, add design changes like filtering/sorting based on error type

Other feedback: 
* Add date/time and maybe user to know when and who
* Add type of feature if there are more than one feature being monitored in the campaign
* Sort list by date/time so newer items are listed at the top
* Add Open in iD or JOSM functionality. Related to #301.

**Comment by dimasciput** [comment]
> Idea: combine the two error feeds, add design changes like filtering/sorting based on error type

@smit1678 , I don't think we can combine both of them. One of them is single page request to https://osmcha.mapbox.com, and the other is from overpass. So for the osmcha error, when you click next it will request to osmcha, but for the attribute completeness the pagination is handled in the front end.

**Comment by smit1678** [comment]
@dimasciput What are the ways that we could change the way we're handling pagination? Can we rethink how we're managing both OSMCHA and Overpass data? Having two tables side by side is a significant usability issue.

**Comment by dimasciput** [comment]
@smit1678 but they have different id, one of them is from https://osmcha.mapbox.com and the other is from http://www.openstreetmap.org. We can display one table at a time, and add something like checkbox. Or maybe just remove one of the table.

**Comment by meomancer** [comment]
hi @smit1678 
both page is really different and as dimas said that the osmcha using pagination. 
And also the big different between osmcha and overpass is osmcha error is from changesets, not looking on feature, so if we combine, the content will be mixed and making confuse to user. 

osm -> feature completeness
osmcha -> changeset suspicious error

My purpose is still distinct it but making tab to change table, between feature completeness and changeset suspicious error

**Comment by cchristelis** [comment]
Hi @smit1678 and @dimasciput, I think there has been one major shift during the past few weeks that puts a new spin onto this discussion. This is the fact that we are now filtering the OSMCha error sets by BB size. This means that where we used to get several hundred pages of OSMCha errors, we now only get a few. This means we could move from a paginated view to a complete view of the OSMCha errors. This would make a combined view at least technically feasible. This means that the only challenge we have is how to meaningfully combine this data into one UI element. Perhaps we should also include @MariaSolovyeva into the discussion.

**Comment by cchristelis** [comment]
@dimasciput, I saw your PR, could you perhaps elaborate on how you combined these and specifically, how you sorted the various errors...

**Comment by cchristelis** [comment]
@dimasciput and @MariaSolovyeva, let's move the comments from the PR to here.

**Comment by MariaSolovyeva** [comment]
Hello  @dimasciput and @cchristelis  , what you think of this variant, where the errors counters can work like tabs to select the errors on the table

![Campaign-errors-table.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46cb959733838aae81a4ba51b652e287645226712501e1673295f127b54778154d555ca9490d5b16aafcdc2fa2e03b25835c0be5d96d597dc36f15bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8f493a1c031188f85d3da28b06.png)

**Comment by cchristelis** [comment]
@dimasciput, just putting @PaulUithol's comment from the PR here: 
> Are we generating those messages? Some could be clearer. E.g. `Error: capacity not found` to `Error: key "capacity" not present`, and don't get what `ceramic to pottery is the accepted tag` would mean? ~ sent from mobile
