### ISSUE TITLE
Improve landing page actions and view

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#312]
From feedback, the current landing page is that it is focused mostly on campaign managers. There is equal weight for initial actions create a campaign or participate in a campaign. Users need more context plus we should look to emphasize participating in a campaign more than creating them. 

* Adjust information hierarchy for new users. Start a Campaign should not be the first information a user reads. Look to help orient and then move into action for a Participant. Start a campaign should be moved into a logged in state. 
* Improve map viz. Redesign markers (consider not using pin markers) for better overlap look. Use a a styled Mapbox base layer. 
* Adjust table information to better clarify what is being tracked, date/time, and an action to participate. Participant information does not make sense (nor does it track the correct number).

**Comment by dimasciput** [comment]
> Improve map viz. Redesign markers (consider not using pin markers) for better overlap look. Use a a styled Mapbox base layer.

@smit1678 , mapbox does have free map, but it has limitation of 50,000 map views / month. https://www.mapbox.com/pricing/. Your call.

**Comment by MariaSolovyeva** [comment]
Here are some rough wireframes for the homepage, so we can discuss it:

![home-wire.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46e09b9726cf94a09decfd0fe64de29b234324676b5ee17e2880b72ab9177e555b0949f948585f4cf4f98f22a3e43862964e49bc8f3900299f7744eeaa880dbe06b0218e4f81b1ba8d4fc9e83520e699c2.png)
![home-wire-cards.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46e09b9726cf94a09decf240a54ff4876b0a65633b0ba92e7391a172fd1723045b0d18a9145c5b12fbac802ba6be34708c550ebfd57f4366846c4ff8e7df46f554f832815d84b0b68b49c0ec3a23e088864f361e070ac4.png)
![home-wire-cards-loggedin.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46e09b9726cf94a09decf240a54ff487644a28742e01a7227ec7af6aaf50740b0a0c0abe4b4a5a4ca9fddb7da3e33874dc5b5ee4d16d577cc63b18a9ea860da313f871d51bdaebe5c01982fa3737e68c854e3b1e011f8ff85e3ca09148cf4abb.png)
![home-wire-logged.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46e09b9726cf94a09decf24fab5af7912d046b313916ac217586f76ae5002e590a5b1cfa440d5b40aafedc22a6b634788a5a02e883694d68d47f40f2ecdd42e64bef62994597b7b5804dc5e83922e18c8c463e1601189bb2.png)
![home-wire-map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46e09b9726cf94a09decf24ea54db2d86b56357c2301a03f32dfa17de7472f03095a1ba8450e5811f5f98923aeb63a798f0e0fffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98a48c7ee3a26ee8b884a3e0c48.png)

What has been updated:
- Two campaign layout variants - horizontal block or card
- Initially we can hide the map
- "Create campaign" and "Manage" button is only visible for the logged in campaign managers
- Show the active campaigns by default, button to show inactive
- Show the nearest campaigns by default, button to show all
- Add radius selection or the nearest campaigns
- Can add priority indicator (from OSM tasking manager)
- More detailed campaign information on the homepage

**Comment by cchristelis** [comment]
Hi @smit1678 and @MariaSolovyeva, my initial thoughts:
- I like the idea of having an option to show only the nearest X rather than showing all nearest. This will improve over time as more campaigns are added.
- I am +1 on the 2 card panels with means it will be closer to what the 1 card per panel will be on a smaller form factor.
- I am +1 on the summary map in the top right. I'm not sure how useful the "hide" map will be since the same outcome can be achieved through scrolling.

All in all I'd be +1 on turning this into a mockup according to the colour guidelines from the new tasking manager.

**Comment by dimasciput** [comment]
Here's my thoughts : 

- I don't think we need map view per row, it will hurts the performance.
- Can we move map panel to the left? People usually scrolling in the right side of the screen.
- Agree with @cchristelis, don't think hide map is useful.

**Comment by cchristelis** [comment]
@dimasciput, we could just pre-render a map and serve it as a static image. esp. if we have a whole earth view then it is just a dot. I'm wondering whether we will actually allow scrolling on the map/maps? they could just be static.

**Comment by dimasciput** [comment]
@cchristelis yes we could server it as a static image, then we need to save the jpeg file to field-campaigner-data too. But why do we need that map view in the row if we can see it the main map view?

For the scrolling, I was thinking about the main map view. I think we should be able to zoom in and out, because those are common behaviors for map.

**Comment by MariaSolovyeva** [comment]
For the map on the top, my idea was initially to hide map, and to show it only if user wants/needs, especially for displaying the nearest campaigns.

**Comment by cchristelis** [comment]
@dimasciput, the idea is to give each of the campaigns their own summary data. It is not possible to see where a campaign is once the user has scrolled down. This will also help out campaigns that have less text added by the campaign managers.

**Comment by dimasciput** [comment]
@cchristelis So like http://tasks.hotosm.org ? Then maybe we don't need the map on the top?

**Comment by MariaSolovyeva** [comment]
@dimasciput , I left the option to show map on the top for the user to see the nearest campaigns. The small thumbnail would not be helpful for this. So when there is a option ticked to show only the nearest campaigns, it should not be too heavy for the server to load only few campaigns on the map?

**Comment by cchristelis** [comment]
maybe it's also nice for logged in users to see their locations on the summary map in the top.

**Comment by MariaSolovyeva** [comment]
yes @cchristelis  I agree

**Comment by MariaSolovyeva** [comment]
Here is the non-manager user view
![Homepage.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46c09b97269282ae8aabf301b44fff9e2c4533317346f67375d1e12eea472f5509581ba54158574cfcff802ef4b22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4b8db0b98f4dc9ec3f2cf5c6.png)

**Comment by MariaSolovyeva** [comment]
Here is the manager view:

- "My" campaigns are added to the selection the top
- "Manage" button added to the cards of the  campaigns created by user

![Homepage-manager.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46c09b97269282ae8aa4b242aa5cf7913b046b313916ac217586f76ae5002e590a5b1cfa440d5b40aafedc22a6b634788a5a02e883694d68d47f40f2ecdd42e64bef62994597b7b4804dc5e8392de18e884e3c1d01199bb2.png)

**Comment by smit1678** [comment]
@MariaSolovyeva Apologies for the slow reply. I like the adjustments with the cards and mini-map views. My main feedback point is that I think we need more context at the top. This landing view needs to orient new comers looking to get an update on a campaign or participate. I think we need to look to answer two questions at the top section: What is this tool? What do I need to do next / how do I get started? The filters and the active campaigns number doesn't communicate this. 

@dimasciput @cchristelis for the mini-maps in the cards, what is the issue with performance? Can't we do this all client-side and not have to add things we need to save and manage in field-campaigner-data (also options like the Mapbox Static API)? I would love to keep how we manage the campaign data as simple as possible.

**Comment by dimasciput** [comment]
@smit1678 I'm using the static image from openstreetmap, so it should be fine now.

**Comment by MariaSolovyeva** [comment]
Hello @cchristelis and @smit1678, do you think of just some text input or something made of data and visual? Attached is how it can look with some descriptions. We will need to make a copy for it.
![Homepage.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46c09b97269282ae8aabf301b44fff9e2c4533317346f67375d1e12eea472f5509581ba54158574cfcff802ef4b22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4a84b2b58a4cc5ed3425f5c6.png)

**Comment by dimasciput** [comment]
Hi @MariaSolovyeva , this is from @smit1678 : 

![mc-1](https://user-images.githubusercontent.com/1979569/30321735-4699b3be-97e1-11e7-823c-db4b054f3b8e.png)

Can you update the mockup?

**Comment by dimasciput** [comment]
@MariaSolovyeva, I tried to move the filtering into search section, but it's just not that good. 
<img width="1424" alt="screen shot 2017-09-12 at 5 44 09 pm" src="https://user-images.githubusercontent.com/1979569/30321973-1c795db8-97e2-11e7-945e-e8cc655588f1.png">

**Comment by MariaSolovyeva** [comment]
hi @dimasciput and @smit1678 ,

please see the updated home
![Homepage-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46c09b97269282ae8aa4ed01e81fe086264c22703d46f96925dde67cbd442e045b5b18ab14515f44f4f1892dafb36e74984019af80330b2b9b645bf9fa9015ad00b22a8a4a85b3be8b44c3e13a26e2889d02.png)

**Comment by smit1678** [comment]
@MariaSolovyeva Can we update the header and footer styles? 
What do you think of trying to reduce down to one intro paragraph with a better title? Something along the lines of: 

![mc-2](https://user-images.githubusercontent.com/796838/30325690-8fdb4ae8-97bd-11e7-94aa-c7d671e9b209.png)

**Comment by cchristelis** [comment]
Something that is confusing me @MariaSolovyeva, is the distinction between the Home and Campaign List in the menu bar.

**Comment by MariaSolovyeva** [comment]
Hi @smit1678 and @cchristelis , please take a look at this.


![homepage-3](https://user-images.githubusercontent.com/10400420/30470640-2905f53c-99fe-11e7-8a7b-c561ce95a979.png)

**Comment by smit1678** [comment]
@MariaSolovyeva Can we update the header and footer as well? Let's use the HOT logo with the tool title for now until (or if) we come up with a specific tool logo and name. Please use this as a guide: https://github.com/hotosm/osm-export-tool2/issues/217#issuecomment-325423661

**Comment by dimasciput** [comment]
@MariaSolovyeva do you have the updated layout?

**Comment by MariaSolovyeva** [comment]
Hello @dimasciput , @cchristelis and @smit1678 , here is the updated header and footer. We need somebody to write the intro copy for the homepage.

![Homepage-4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46c09b97269282ae8aa4eb01e81fe086264c22703d46f96925dde67cbd442e045b5b18ab14515f44f4f1892dafb36e74984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85b3bb894ac3e93f24ee839d02.png)

**Comment by PaulUithol** [comment]
Looks pretty good. In the header, is there any different behavior between clicking on the logo/name, 'Home' and 'Campaign list'? If not, can we reduce the options there?

**Comment by MariaSolovyeva** [comment]
Thank you @PaulUithol , of course that makes sense about  logo/name, 'Home' and 'Campaign list'?, just updated it. This is what @cchristelis was pointing at too, but I didn't read it good.
![Homepage-4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54aa80294f6dad0200170914/125516c66e82c728ace21e0d46c09b97269282ae8aa4eb01e81fe086264c22703d46f96925dde67cbd442e045b5b18ab14515f44f4f1892dafb36e74984019af80330b2b9b645bf9fa9015ad00b32a8a4a85b0bc8c4cc1e03a21ee8f9d02.png)

**Comment by cchristelis** [comment]
@ann26, can you please confirm that our latest version is in-line with the final mock-up?

**Comment by ann26** [comment]
yes @cchristelis
