### ISSUE TITLE
How remote projects are shown and integrated into the map view

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#314]
Currently we just show the remote project on the map and integrated into the side bar. This view feels a little cluttered. This could be just a design issue for how the layers are styled on the map. 

![map campaigner - test remote campaign 2017-09-04 17-05-14](https://user-images.githubusercontent.com/796838/30037648-5f004d40-9193-11e7-81a9-a4ac0d6c9757.png)

**Comment by cchristelis** [comment]
# Proposed Solution

Get a colour pallet that works well between the various data layers.

**Comment by cchristelis** [comment]
This has been covered in https://github.com/hotosm/field-campaigner/issues/308#issuecomment-331359007
