### ISSUE TITLE
Improve Maps.me experience by opening AOI into app

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#317]
Some feedback from users when using Maps.me after visiting the dashboard page: 

> What did you think you’ll see when you clicked the Maps.me button? 
> 
> The AOI of the campaign open up in Maps.me
Instead it located the Maps.me app in the App Store (using iOS)
Opened Maps.me, but nothing happened

Idea proposed: open a bookmark or KML file directly into Maps.me to show area that should be mapped. This seems to be supported by Maps.me: https://support.maps.me/hc/en-us/articles/207895029-How-can-I-import-bookmarks-

**Comment by cchristelis** [comment]
@dimasciput will you follow up on the iOS side.
@meomancer will you follow up on the Android side.

**Comment by dimasciput** [comment]
@smit1678 @cchristelis 
I have tested this on iOS, you can open the .kml file in Maps.me
![img_0407](https://user-images.githubusercontent.com/1979569/30148819-61df955a-93cf-11e7-94e3-f05a6b4d07a2.PNG)

But you will need have Maps.me installed ( there's no way browser will know if you have it installed or not), and if you have it installed it will not automatically open the maps.me. So I think maybe we need change the button name.

**Comment by cchristelis** [comment]
@dimasciput, maybe we just note that in some helper text. Maybe this is interesting to note for @MariaSolovyeva while she is thinking about the call to actions on the UI.

**Comment by cchristelis** [comment]
Hi @meomancer, for android have a look at: https://stackoverflow.com/a/12901352/1158060

**Comment by dimasciput** [comment]
Added in https://github.com/hotosm/field-campaigner/pull/401
