### ISSUE TITLE
Implementing UI Updates

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#330]
# Problem

The UI is being revised based on user feedback.

# Proposed Solution

Implement the updates. This ticket will also contain paper cuts resulting from the update.

**Comment by cchristelis** [comment]
# Paper Cuts
- All/Closest dropdown seems broken. On chrome it always jumps back to all. 
- The pin on the minimap makes the campaign appear further north east than it is.

**Comment by dimasciput** [comment]
> The pin on the minimap makes the campaign appear further north east than it is.

Can you explain more about this?

**Comment by cchristelis** [comment]
<img width="631" alt="screen shot 2017-09-12 at 3 57 54 am" src="https://user-images.githubusercontent.com/2319504/30304613-9d8e7c2c-976e-11e7-8291-a0fb6ad151a3.png">

The popup looks like a polygon.

**Comment by dimasciput** [comment]
I couldn't change the markers, this is from the provider. http://staticmap.openstreetmap.de

**Comment by dimasciput** [comment]
All of these issues are solved, closing it now.
