### ISSUE TITLE
No Cards on the Landing Page

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#332]
# Problem

When I open up https://staging.campaign.kartoza.com/ I get a black page.

# Proposed Solution 

Investigate and fix.

**Comment by dimasciput** [comment]
Sorry, I couldn't reproduce this. I got results from that page. Could you try it @meomancer

**Comment by meomancer** [comment]
hi @dimasciput @cchristelis 
i see cards on landing page too

**Comment by cchristelis** [comment]
@dimasciput and @meomancer this happens only when the user is not logged in...

**Comment by cchristelis** [comment]
and you deny sharing your location.
