### ISSUE TITLE
Logged out users cannot see nearest campaigns

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#349]
# Problem

As a logged out user. When trying to select nearest campaigns on the landing page it keeps jumping back to all. I'm expecting this to switch to nearest.

# Proposed Solution

Allow logged out users to show nearest based on their browser location.

**Comment by dimasciput** [comment]
@cchristelis Did you allow the browser to get your location? If not, then there's no way we can get the nearest campaigns.

**Comment by cchristelis** [comment]
This needs to communicate to the user, otherwise a user experiences it like a bug.
