### ISSUE TITLE
In campaign setup, add custom input to data types

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/field-campaigner#358]
So we don't constrain people to just collecting the types of data we've pre-specified in the "Types" of data to collect. Expected behavior something like:

- Click the item in the list labeled "Other..", "Custom..", something like that.
- You can now input your own key/value for the feature you want to collect data on (like the amazing "trees in Ottawa live demo" with `natural=tree` at the Summit :) )
- And add tags for that feature

**Comment by cchristelis** [comment]
# Custom Tags

When tags have multiple values, how do we show this/ do we show this on the button:

<img width="804" alt="screen shot 2017-09-26 at 10 51 03 am" src="https://user-images.githubusercontent.com/2319504/30851346-a9ea4a4c-a2a8-11e7-9813-8dd6d194cf6c.png">

**Comment by cchristelis** [comment]
# Are Surveys Saved?

Should the surveys be saved to git:
- These might be useful for other users?
- This might cause clutter?
