### ISSUE TITLE
Write intro text

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#360]
Need to replace lorem ipsum with real text. 

![map campaigner 2017-09-20 11-57-38](https://user-images.githubusercontent.com/796838/30640466-f3b374f8-9dfa-11e7-8870-15689b4651d9.png)

**Comment by ann26** [comment]
Hi @smit1678 @PaulUithol @cchristelis ,
Do you have the text for this?

**Comment by cchristelis** [comment]
@ann26, Let's start with @smit1678 and @PaulUithol can improve on it:

> This tool is aimed at managing and monitoring field data collection campaigns. Campaign managers may use this tool to setup new and review ongoing and completed campaigns. Various progress and quality matrices are available. Data collectors can fiend nearby campaigns to participate in.

**Comment by PaulUithol** [comment]
"MapCampaigner is aimed at managing and monitoring field data collection campaigns.
Campaign managers may use this tool to setup new and review ongoing and completed campaigns
Mappers can find nearby campaigns to participate in."?

**Comment by ann26** [comment]
Thank you @cchristelis and @PaulUithol , I will update it in #393
