### ISSUE TITLE
GeoJson upload broken

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#362]
# Problem 

The GeoJson upload seems broken.

**Comment by dimasciput** [comment]
Where did you test it? I just tried it and it was working fine.
![field](https://user-images.githubusercontent.com/1979569/30841006-88a49c2e-a2a4-11e7-9c5e-86b5ea9d76b7.gif)

**Comment by cchristelis** [comment]
thanks, I also re-tested, it is working now.
