### ISSUE TITLE
Should we temporarily pre-define Managers

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#363]
# Problem

We are currently relying on the public Overpass, until the dedicated HOT Overpass instance is available, which means we may have performance issues when too many users are adding data.

# Discussion

Should we while waiting on the dedicated Overpass, limit the number of potential contributors? This could be done by pre-defining allowed managers?

**Comment by cchristelis** [comment]
Let's do this.

**Comment by meomancer** [comment]
hi @cchristelis 
what is the decision for solution for this?

**Comment by cchristelis** [comment]
@meomancer, let's revert to our original approach, where we have users on a file...

**Comment by PaulUithol** [comment]
Could you add me to the list please?

Right now, the message it displays now if you don't have permission is not that helpful: "Sorry! The request was valid, but the server is refusing action. The user might not have the necessary permissions.".

This should point out that a) there is a select set of users that can create campaigns, and b) who to contact if you'd like to set up a campaign

**Comment by PaulUithol** [comment]
I thought there was a dedicated HOT overpass now though? Is that original concern still an issue?

**Comment by smit1678** [comment]
> I thought there was a dedicated HOT overpass now though? Is that original concern still an issue?

It's still be tested and monitored, plus even when it's stable, we plan to monitor the impact of the Field Campaigner on it so we can understand the impact of it on the Export tool. So by limiting project managers, then we can control the amount of campaigns that are created. 

> Could you add me to the list please?

Yes, we'll start with active projects and project managers. 

> This should point out that a) there is a select set of users that can create campaigns, and b) who to contact if you'd like to set up a campaign

Agreed, we should have it display instructions for who to contact.

**Comment by PaulUithol** [comment]
Would it make sense to (auto)sync this list with the TM list?
