### ISSUE TITLE
Handling large amount of users on user engagement graphs

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#365]
@MariaSolovyeva @dimasciput How do we want to handle the user engagement graphs when we have a lot of users? Looks like this breaks when it's above 10 or 11 but that's dependent on the username length. 

![map campaigner - financial services in mbale 2017-09-25 19-06-50](https://user-images.githubusercontent.com/796838/30895722-28b55bb2-a3a0-11e7-872f-6e3542105d3d.png)

**Comment by dimasciput** [comment]
This is from the chart.js library, so I will try to customize the legend. Maybe change the location of the legend.
