### ISSUE TITLE
Show map all the time on the front page

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#366]
Sometimes it loads, sometimes it doesn't. Some filter views it shows, sometimes it doesn't. 

@dimasciput Can you explain the map visibility on the front page? Should we just keep it on all the time since we've designed the header and main text to factor for the map?

**Comment by dimasciput** [comment]
I think this is design decision from Maria, if you select view all then the map is hidden. But if you select nearest/inactive it will display the map. I'll change it to show it all the time.
