### ISSUE TITLE
Completeness not 100% although no error but it is just warning

### ISSUE THREAD

**Issue by meomancer** [hotosm/field-campaigner#370]
# Problem
When feature just has warning, it is not indicated as complete. I'm not sure it is bug or not.

![selection_013](https://user-images.githubusercontent.com/4530905/30898772-2091a828-a387-11e7-9048-8744d4bd0cb3.png)

**Comment by dimasciput** [comment]
It's not bug, currently I count warning as not complete. But I can change this if we want to count it as complete feature.

**Comment by cchristelis** [comment]
My thoughts are that the feature is complete, but still show this feature in the error table and popup.

**Comment by cchristelis** [comment]
Maybe add a filter on the errors table `include warnings`?

**Comment by cchristelis** [comment]
@smit1678 and @PaulUithol, do you agree with the logic `no errors only warnings === 100% complete`

**Comment by smit1678** [comment]
@cchristelis I think I'm good with that approach. 👍

**Comment by cchristelis** [comment]
Hi @ann26, could you please have a look at this.

**Comment by ann26** [comment]
ok @cchristelis

**Comment by ann26** [comment]
@cchristelis this is fixed in #373

**Comment by cchristelis** [comment]
Thanks @ann26
