### ISSUE TITLE
Browser performance

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#385]
# Problem

The browser seems to hang when opening this campaign: http://campaigns.hotosm.org/campaign/a8df332e22d24349b5874ea185fbe012

# Proposed Solution

- Profile and diagnose the issue. 
- Optimize where possible.
- Given user feedback through a throbber (?) that things are happening.

**Comment by ann26** [comment]
Hi @cchristelis 
The possible cause of the issue is it use a lot of function and each function collects a lot of data, as shown below:
![screenshot from 2017-11-06 18-20-27](https://user-images.githubusercontent.com/26101337/32441194-0f275152-c329-11e7-9be4-4d3d56998029.png)

**Comment by ann26** [comment]
Other problem that I found was some functions failed to load, so it made the page stuck at loading it.

**Comment by ann26** [comment]
Hi @cchristelis ,

I think the main cause of this is that there are a lot of functions on the ajax success (https://github.com/hotosm/field-campaigner/blob/develop/flask_project/campaign_manager/static/js/detail/insight_functions.js#L321)
One that is quite heavy is the `renderFeatures` function as the data from osm is not geojson, so it is converted into geojson in front end.
@meomancer suggested that perhaps it is better to convert it into geojson in backend when it downloads osm data. What do you think @cchristelis ?

**Comment by cchristelis** [comment]
@ann26, yes, try doing that conversion server side and give a quantitative performance comparison. Also, please investigate whether we could render these without converting them at all?

**Comment by dimasciput** [comment]
The browser is not hang anymore, and throbber has been added. 
The problem is because we adding thousands of data directly to the datatable. We can still improve the performance, but I think we have fixed this issue.
