### ISSUE TITLE
Text/documentation additions

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/field-campaigner#391]
Need text addition/improvement in some places:

1. Main text (home page, underneath "Map Campaigner" and above "Active campaigns:"); #360 

2. Short description on http://campaigns.hotosm.org/create

3. On a specific campaign page; some explanation on what you see

4. An "About" page or documentation

**Comment by ann26** [comment]
Where would be best to add the short description @PaulUithol @MariaSolovyeva @smit1678 ?
![screencapture-0-0-0-0-5000-create-1510565727889](https://user-images.githubusercontent.com/26101337/32718818-e20e2732-c890-11e7-9536-2fff3ef4fa78.png)

> On a specific campaign page; some explanation on what you see
@PaulUithol Does specific campaign page means the campaign details? If yes, then are the explanations describing what's displayed on the tab? or in the map?
