### ISSUE TITLE
View per campaign information

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#4]
Needs: 
  * Simple overview of campaign, purpose, what is being collected
  * Quick start for people on mobile to get mapping
  * Serve as the main view for linking to the campaign from external resources (i.e. linking from Maps.me)

**Comment by cchristelis** [comment]
@smit1678, in terms of mobile, are these users going to be using the web interface or are we targeting a specific mobile application?

**Comment by smit1678** [comment]
@cchristelis Following up here. I think we stick to web interface use. From the Maps.me use case, they can link to a specific web page from a push notification.
