### ISSUE TITLE
Refused access 

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#403]
Related to https://github.com/hotosm/field-campaigner/pull/402 and #363, it looks like my user 'nsmith' doesn't have access to edit or create campaigns, even though my user is on the list of approved users. 

@dimasciput are you seeing this as well? 

![map campaigner 2017-11-29 14-15-09](https://user-images.githubusercontent.com/796838/33379634-a5c47718-d510-11e7-9e74-687ef5ff6705.png)

**Comment by dimasciput** [comment]
@smit1678 sorry, I didn't make this clear. You need to create a file named 'managers.txt'  in campaign-data folder. And put your username there.

**Comment by smit1678** [comment]
Ok so no need for the osm-users.txt file anymore?

Nate Smith
@nas_smith
________________________________

**Comment by smit1678** [comment]
@dimasciput Ok, I've figured out where to put the `managers.txt` file. It looks like it works correctly for creating campaigns, but is not allowing me to edit campaigns. 

What was the thinking behind the decision to put it in the `field-campaigner-data` folder versus within the application folder like the `osm-user.txt` file? Also is the code needed for the `osm-user.txt` file anymore?

**Comment by dimasciput** [comment]
Because I thought this is count as field campaigner data. We don’t need the osm users file anymore, I will remove it from repo. 

For the edit function, I will try to fix it on the weekend.

**Comment by dimasciput** [comment]
Fixed in https://github.com/hotosm/field-campaigner/pull/404
