### ISSUE TITLE
path error in README.md

### ISSUE THREAD

**Issue by Dragneel7** [hotosm/field-campaigner#415]
To Build the Field-Campaigner, it is mentioned to run the commands in directory `/osm-reporter/deployment` which I think should be `/field-campaigner/deployment`.
MakeFile has project Id `osmreporter` which needs to be replaced by `field-campaigner`(Please correct me if I am wrong).

@smit1678 What do you think about it?

**Comment by smit1678** [comment]
👍  thanks
