### ISSUE TITLE
Add surveys by means of YAML

### ISSUE THREAD

**Issue by AlwynSmit** [hotosm/field-campaigner#448]
# Problem

Currently, most of the tools in the OSM suite use yaml to configure the feature and element selection. As such users are very familiar with this representation and this would be a better interface than the current version. Have a look at https://export.hotosm.org/en/v3/learn/yaml 

# Proposed Solution

Allow users to edit their campaign survey data directly in an inline yaml editor (while still allowing easy addition of new surveys).

**Comment by meomancer** [comment]
hi @AlwynSmit 
could you explain this ticket?
