### ISSUE TITLE
Show field mapping coverage

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#5]
Needs: 
  * Show how much of an area has been covered, in terms of features mapped or areas visited.
  * Highlight areas where information has not been collected.

Challenges to think through: 
  * How to track and show areas where surveyors have visited but no features collected? For example, an area of a city that does not have any health facilities.

**Comment by cchristelis** [comment]
The campaign managers could upload or digitise vectors to indicate which areas have been visited by teams in the campaign, although this is manual, it'll give a definitive area. 

In conjunction with this approach, ​we could try and automatically deduce where teams/users have been by looking at activity in various areas, but this will at best give a probable result.
