### ISSUE TITLE
Creator of campaign can't edit a campaign if he is not a manager

### ISSUE THREAD

**Issue by dimasciput** [hotosm/field-campaigner#58]
Currently when creating a campaign, user need to pick the managers. If they didn't pick themselves as a manager, they won't have a capability to edit the campaign later. Is this a problem?

**Comment by cchristelis** [comment]
Perhaps we should default to include the campaign author in the list of campaign managers, so that they have to explicitly remove themselves rather than explicitly add themselves. Perhaps @smit1678 also has some thoughts on this?

**Comment by smit1678** [comment]
👍  to the default the campaign author as the campaign manager, I think that makes the most sense. 

I'm not sure if we want to allow a user who created a campaign to then remove themselves as the manager. We don't want manager-less campaigns.

**Comment by dimasciput** [comment]
Ok, I will make author as default manager. And make manager as a required attribute, so at least campaign will have one manager.
