### ISSUE TITLE
Show remote mapping coverage

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#6]
A typical first step before any field mapping is remote mapping. Would be helpful to see the coverage of remote mapping conducted through a Tasking Manager project.

**Comment by cchristelis** [comment]
Possible one to many relationship. We sometimes add many tasking manager projects to cover one campaign.

**Comment by smit1678** [comment]
Tasking Manager 3 API docs are here (staging site at the moment): http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api-docs/swagger-ui/index.html?url=http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/docs. 

Example project stats: http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/v1/stats/project/2648

Example project info for displaying on a map: http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/v1/project/2648

**Comment by cchristelis** [comment]
We will either allow the user to add one or more remote mapping tasks against the campaign. Or we will generate one to match the campaign.

**Comment by dimasciput** [comment]
Hi @smit1678 could you give me some insight on what is the workflow for this? Thanks.

**Comment by cchristelis** [comment]
Hi @dimasciput, I think this is related to #119. Let's hang on this until we have the diagrams.

**Comment by dimasciput** [comment]
The diagram: 

![27428389-2296245a-5742-11e7-9951-73b193d049fe](https://user-images.githubusercontent.com/1979569/27822932-8f736f72-60d1-11e7-8710-00bf52a56c74.png)

**Comment by cchristelis** [comment]
@dimasciput, @MariaSolovyeva is busy developing the UI around this. We are still busy finalizing the effort. I'll ask @MariaSolovyeva to attach the final version here.

**Comment by dimasciput** [comment]
@cchristelis how to auto generate remote mapping tasks against the campaign? based on the area?

**Comment by smit1678** [comment]
From a priority perspective, for now we should just integrate linking to the tasking manager project, showing the percentage complete, and area of the map that was covered by the remote mapping. 

We should separate the autogenerating projects into another ticket and should push that further down the roadmap.

**Comment by dimasciput** [comment]
Hi @smit1678, I tried this api but couldn't get it to work, http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api-docs/swagger-ui/index.html?url=http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/docs#!/search/get_api_v1_projects_within_bounding_box. 

I don't know where to find the auth token.

**Comment by dimasciput** [comment]
Added in https://github.com/hotosm/field-campaigner/pull/151
