### ISSUE TITLE
Error when creating table with big data

### ISSUE THREAD

**Issue by meomancer** [hotosm/field-campaigner#63]
# Problem
On insights function for creating table, if data is big, it will make machine run so hard and creates lag. And after that, giving error `Uncaught RangeError: Maximum call stack size exceeded`

test boundary
[test_boundary.zip](https://github.com/hotosm/field-campaigner/files/1040869/test_boundary.zip)

and do for Campaign 2 

# Solution
Maybe we split data and render it to table by loop?

**Comment by cchristelis** [comment]
:+1: for pagination server side.

**Comment by cchristelis** [comment]
This is implicitly handled by #93
