### ISSUE TITLE
Error check for completeness of information

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#7]
Of the features within AOI, how many have the complete information being collected? 

Completeness is defined by the attributes you are collecting. If you are collecting name, opening time, and operator but only collect name, you are missing 2 of the 3 attributes.

**Comment by dimasciput** [comment]
@smit1678 currently this is how we calculate completeness information 
https://github.com/hotosm/field-campaigner/wiki/Insights-Function#2-feature-attribute-completeness

Is that enough? Or we need to add another attributes? And what attributes?

**Comment by dimasciput** [comment]
@smit1678 I added check operator in #165 

![screen shot 2017-07-11 at 1 45 16 pm](https://user-images.githubusercontent.com/1979569/28054534-5ff509b8-663f-11e7-870c-b510d1bee112.png)

![map_campaigner](https://user-images.githubusercontent.com/1979569/28054522-52d843f8-663f-11e7-855e-d76aca02359d.png)

**Comment by smit1678** [comment]
@dimasciput Ok great. To follow up: 

> Is that enough? Or we need to add another attributes? And what attributes?

Feature completeness should be based off of the features and tags that are defined when creating the campaign. So completeness will change between campaigns. In our [example health facility survey](https://gist.github.com/smit1678/a355159f4efba0f91d4a105a905a7296), having any one of those features missing should through an error.

**Comment by dimasciput** [comment]
@smit1678 I think this will be solved by new Irwan's PR 
https://github.com/hotosm/field-campaigner/pull/166
