### ISSUE TITLE
Git vs Git

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#79]
# Problem

We are currently adding our git code and our git data to the same repository. This will cause problems for users who want to set up the system in different environments. 

# Proposed Solution

Split the data and the code repos.

**Comment by smit1678** [comment]
@cchristelis @meomancer Let me know when you need a repo on HOT's account for the data

**Comment by meomancer** [comment]
hi @smit1678 
is there a repo for our campaign data?

**Comment by smit1678** [comment]
@meomancer Done! https://github.com/hotosm/field-campaigner-data
