### ISSUE TITLE
Error check for capitalization issues

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#8]
Review and flag features that are collected with capitalization issues.

**Comment by dimasciput** [comment]
Hi @smit1678 could you elaborate more about this issue? I'm not sure I understand.

**Comment by smit1678** [comment]
@dimasciput Will try to find some more real world examples, but main point is around ensuring data entered into OSM has correct capitalization, especially for names. 

One example: 

A tea shop in Dar es Salaam: http://www.openstreetmap.org/node/3431294229. Currently this is wrong capitalization: `name=mama ntilie`. 

Should be: `name=Mama Ntilie`.

**Comment by PaulUithol** [comment]
We've corrected most of these in the data; but you'll also find people tagging this in a format such as `name=MAMA NTILIE` sometimes.

Are we distinguishing different levels of errors, say errors and warnings?

**Comment by dimasciput** [comment]
@smit1678 but what if the name comes from non english language? For example, http://www.openstreetmap.org/way/405317934

**Comment by dimasciput** [comment]
And what about capitalization for this name, http://www.openstreetmap.org/way/249486506. 
I think `Farol do Bugio` has correct capitalization, but with your rule this will count as an error?

**Comment by smit1678** [comment]
@dimasciput Don't disagree at all for both of those situations and I don't have a good answer other than we'll need to do some logic that covers or flags a majority of the situations. Since most languages have some type of capitalization, it'll be hard to cover every situation. 

Maybe we start with Roman/Latin script languages? 

In situations like `Farol do Bugio`, perhaps this is flagged as a mixed case situation and it needs to be reviewed.

**Comment by dimasciput** [comment]
Added in this PR #165

![screenshot_7_11_17__1_47_pm](https://user-images.githubusercontent.com/1979569/28054575-99f59060-663f-11e7-8ce2-14ed5c17c6ce.png)
