### ISSUE TITLE
Error check review workflow

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#9]
From the flagged features using error checking in #7 and #8, enable a workflow to open flagged changesets/features in iD or JOSM to make edits. This isn't just a manager workflow, could be open to anyone participating in the campaign.

**Comment by cchristelis** [comment]
# Proposed Solution

In all error and quality functions, for features that don't attain the required quality or have errors, under "More info" add links to the feature in OSM.
This will allow Users to fix these issues.
