### ISSUE TITLE
logging in

### ISSUE THREAD

**Issue by gubuntu** [hotosm/field-campaigner#99]
I had to log in twice before I was taken back to the campaigner screen. 

The second time OSM asked for app access permission. 

It should be just one seamless step....

**Comment by dimasciput** [comment]
Yes, you will need to login in openstreetmap first then you need to grant access. I think most oauth process will be like that if you haven't logged in yet. Like twitter, facebook, etc.

**Comment by gubuntu** [comment]
I tried in Firefox and it worked seamlessly (although it should not be 'Dimas-osm-reporter' requesting access)

My OP was after trying in Safari where it didn't open in a popup but in a separate tab and was a lot clunkier.

**Comment by dimasciput** [comment]
@gubuntu did you open it from mobile? Because I tried it in safari desktop, popup opened.

**Comment by gubuntu** [comment]
no, desktop
